# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: coherentsolutions/service-fabric-run-tests:7.2.476.1-3.1

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src/Code.sln'
    feedsToUse: 'select'
  displayName: 'Restore'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Code.sln'
    arguments: '-c Release --no-restore'
  displayName: 'Build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/Code.sln'
    arguments: '-c Test --no-build --no-restore'
  displayName: 'Test'