# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo -e ''FROM coherentsolutions/service-fabric-run-tests:latest\nWORKDIR .\nCOPY ./* ./\nRUN dotnet restore\nRUN dotnet build -c Release --no-restore\ndotnet test -c Test --no-build --no-restore'' >> /Dockerfile"'
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'